In [8]:
import tensorflow as  tf
import tensorflow.keras as keras

import numpy as np

In [9]:
# keras.__version__

In [10]:
import os

# folder_path = "D:\yun\yun-python\딥러닝(kmooc 연습)\포켓몬 이미지"
folder_path = "D:\yun\yun-python\deeplearning\pokemon-train-image"
folder_list = os.listdir(folder_path)
print(folder_list)
print(f'Total number of categories: {len(folder_list)}')

counts = {}
for c in folder_list:
    counts[c] = len(os.listdir(os.path.join(folder_path, c)))
    
print(f'Total number of images in dataset: {sum(list(counts.values()))}')

# categories=['강철', '격투', '고스트', '노멀', '독', '드래곤', '땅', '물', '바위', '벌레', '불꽃', '악', '얼음', '에스퍼', '전기', '페어리', '풀']

categories=['bug', 'dragon', 'electricity', 'esp', 'evil', 'fairy', 'fight', 'fire', 'ghost', 'grass', 'ice', 'land', 'normal', 'posion', 'rock', 'steel', 'water']

['bug', 'dragon', 'electricity', 'esp', 'evil', 'fairy', 'fight', 'fire', 'ghost', 'grass', 'ice', 'land', 'normal', 'posion', 'rock', 'steel', 'water']
Total number of categories: 17
Total number of images in dataset: 55588


In [11]:
imbalanced = sorted(counts.items(), key = lambda x: x[1], reverse = True)
print(imbalanced)

[('water', 6410), ('normal', 5096), ('fire', 4101), ('bug', 4001), ('grass', 3916), ('land', 3448), ('esp', 3177), ('posion', 3086), ('electricity', 3046), ('rock', 2905), ('fight', 2904), ('ice', 2670), ('dragon', 2397), ('ghost', 2356), ('steel', 2305), ('evil', 2072), ('fairy', 1698)]


In [12]:
# caltech_dir = "..\deeplearning\pokemon-image"
caltech_dir = "pokemon-train-image"
categories=['bug', 'dragon', 'electricity', 'esp', 'evil', 'fairy', 'fight', 'fire', 'ghost', 'grass', 'ice', 'land', 'normal', 'posion', 'rock', 'steel', 'water']
nb_classes = len(categories)

In [13]:
# !dir .

In [14]:
# 이미지 전처리

from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image

datagen = ImageDataGenerator(rescale=1./255,
      rotation_range=10,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True,
      vertical_flip=False,
      fill_mode='nearest')

generator = datagen.flow_from_directory(
        # 타깃 디렉터리
        caltech_dir,
        # 모든 이미지를 150 × 150 크기로 바꿉니다
        target_size=(150, 150),
        batch_size=20,
        class_mode='categorical')

val_datagen = ImageDataGenerator(rescale=1./255,
                                 rotation_range = 30,
                                 width_shift_range=0.2,
                                 height_shift_range=0.2,
                                 shear_range=0.2,
                                 zoom_range=0.1,
                                 horizontal_flip=True,
                                 vertical_flip=False,
                                 fill_mode='nearest')

val_generator = val_datagen.flow_from_directory(
                                          caltech_dir,
                                          target_size=(150,150),
                                          batch_size=20,
                                          class_mode='categorical')

Found 55588 images belonging to 17 classes.
Found 55588 images belonging to 17 classes.


In [23]:
class_names = generator.class_mode
print(class_names)

categorical


In [23]:
from keras.models import Sequential
from keras.layers import *
from keras import optimizers

In [30]:
# 모델 구성

model = Sequential()
model.add(Conv2D(64, kernel_size=(3,3), padding='same', input_shape=(150,150,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(128, kernel_size=(3,3),padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))

model.add(Conv2D(256, kernel_size=(3,3), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(17, activation='softmax'))

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 150, 150, 64)      1792      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 75, 75, 64)        0         
_________________________________________________________________
dropout_12 (Dropout)         (None, 75, 75, 64)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 75, 75, 128)       73856     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 37, 37, 128)       0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 37, 37, 128)       0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 37, 37, 256)      

In [16]:
# 모델 구성

model2 = Sequential()
model2.add(Conv2D(64, kernel_size=(3,3),padding='same', input_shape=(150,150,3), activation='relu'))
model2.add(MaxPooling2D(pool_size=(2,2)))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))

model2.add(Conv2D(64, kernel_size=(3,3),padding='same', activation='relu'))
model2.add(MaxPooling2D(pool_size=(2,2)))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))

model2.add(Conv2D(128, kernel_size=(3,3),padding='same', activation='relu'))
model2.add(MaxPooling2D(pool_size=(2,2)))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))

model2.add(Conv2D(256, kernel_size=(3,3),padding='same', activation='relu'))
model2.add(MaxPooling2D(pool_size=(2,2)))
model2.add(Dropout(0.2))

model2.add(Flatten())
model2.add(Dense(256, activation='relu'))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))
model2.add(Dense(17, activation='softmax'))

In [17]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 150, 150, 64)      1792      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 75, 75, 64)        0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 75, 75, 64)        256       
_________________________________________________________________
dropout_5 (Dropout)          (None, 75, 75, 64)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 75, 75, 64)        36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 37, 37, 64)        0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 37, 37, 64)       

In [18]:
#모델 학습 설정
model2.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [7]:
# 이미지 전처리

from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image

datagen = ImageDataGenerator(rescale=1./255,
      rotation_range=20,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True,
      vertical_flip=True,
      fill_mode='nearest')

generator = datagen.flow_from_directory(
        # 타깃 디렉터리
        caltech_dir,
        # 모든 이미지를 150 × 150 크기로 바꿉니다
        target_size=(150, 150),
        batch_size=40,
        shuffle=True,
        class_mode='categorical')

val_datagen = ImageDataGenerator(rescale=1./255,
                                 rotation_range = 40,
                                 width_shift_range=0.2,
                                 height_shift_range=0.2,
                                 shear_range=0.2,
                                 zoom_range=0.2,
                                 horizontal_flip=True,
                                 vertical_flip=True,
                                 fill_mode='nearest')

val_generator = val_datagen.flow_from_directory(
                                          caltech_dir,
                                          target_size=(150,150),
                                          batch_size=40,
                                          class_mode='categorical')

Found 55588 images belonging to 17 classes.
Found 55588 images belonging to 17 classes.


In [8]:
from keras.models import Sequential
from keras.layers import *
from keras import optimizers

In [9]:
# 모델 구성

model3 = Sequential()

model3.add(Conv2D(32, kernel_size=(3,3),padding='same', input_shape=(150,150,3), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2,2)))
model3.add(BatchNormalization())
model3.add(Dropout(0.2))

model3.add(Conv2D(64, kernel_size=(3,3),padding='same', activation='relu'))
model3.add(MaxPooling2D(pool_size=(2,2)))
model3.add(BatchNormalization())
model3.add(Dropout(0.2))

model3.add(Conv2D(128, kernel_size=(3,3),padding='same', activation='relu'))
model3.add(MaxPooling2D(pool_size=(2,2)))
model3.add(BatchNormalization())
model3.add(Dropout(0.2))

model3.add(Conv2D(256, kernel_size=(3,3),padding='same', activation='relu'))
model3.add(MaxPooling2D(pool_size=(2,2)))
model3.add(Dropout(0.2))

model3.add(Flatten())
model3.add(Dense(256, activation='relu'))
model3.add(BatchNormalization())
model3.add(Dropout(0.2))
model3.add(Dense(17, activation='softmax'))

In [10]:
#모델 학습 설정
model3.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [15]:
# fig_generator
model3.fit_generator(
    generator,
    steps_per_epoch=200,
    epochs=300,
    validation_data=val_generator,
    validation_steps=70)

3s/step - loss: 2.3202 - accuracy: 0.2875 - val_loss: 2.3520 - val_accuracy: 0.2665
Epoch 14/150
150/150 [==============================] - 500s 3s/step - loss: 2.3098 - accuracy: 0.2805 - val_loss: 2.3434 - val_accuracy: 0.2690
Epoch 15/150
150/150 [==============================] - 501s 3s/step - loss: 2.3017 - accuracy: 0.2912 - val_loss: 2.3043 - val_accuracy: 0.2835
Epoch 16/150
150/150 [==============================] - 509s 3s/step - loss: 2.3426 - accuracy: 0.2698 - val_loss: 2.4429 - val_accuracy: 0.2465
Epoch 17/150
150/150 [==============================] - 500s 3s/step - loss: 2.2897 - accuracy: 0.2935 - val_loss: 3.2812 - val_accuracy: 0.1410
Epoch 18/150
150/150 [==============================] - 513s 3s/step - loss: 2.2673 - accuracy: 0.2971 - val_loss: 2.4199 - val_accuracy: 0.2650
Epoch 19/150
150/150 [==============================] - 517s 3s/step - loss: 2.2987 - accuracy: 0.2842 - val_loss: 2.3310 - val_accuracy: 0.2770
Epoch 20/150
150/150 [========================

In [1]:
from tensorflow.python.keras.models import load_model

In [45]:
model=load_model('model2.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 150, 150, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 75, 75, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 75, 75, 32)        128       
_________________________________________________________________
dropout (Dropout)            (None, 75, 75, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 75, 75, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 37, 37, 64)        0         
_________________________________________________________________
batch_normalization_1 (Batch (None, 37, 37, 64)        2

In [4]:
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image

In [236]:
img=image.load_img('pokemon-test-image\water\야돈_3.jpg', target_size=(150, 150))
type(img)

PIL.Image.Image

In [242]:
x = image.load_img('pokemon-test-image/fire/윈디_120.jpg', target_size=(150, 150))
x = image.img_to_array(x)
x = x.reshape((1,) + x.shape)
x = x/255.

In [243]:
x.shape

(1, 150, 150, 3)

In [244]:
predict=model.predict(x).flatten()
predict

array([0.01801904, 0.00284082, 0.01502389, 0.00885601, 0.03310708,
       0.02035785, 0.04623378, 0.2191215 , 0.10316587, 0.01619275,
       0.00770238, 0.04910393, 0.3172349 , 0.00828799, 0.11408798,
       0.00686288, 0.01380135], dtype=float32)

In [197]:
np.sort(predict)[-1:]

array([0.2191215, 0.3172349], dtype=float32)

In [183]:
s=np.argsort(predict)
p1=np.argmax(predict)


array([ 1, 15, 10, 13,  3, 16,  2,  9,  0,  5,  4,  6, 11,  8, 14,  7, 12],
      dtype=int64)

In [250]:
{categories[p1]: 100*np.sort(predict)[-1:].round(3)}

{'노멀': array([31.7], dtype=float32)}

In [153]:
s

array([[ 1, 15, 10, 13,  3, 16,  2,  9,  0,  5,  4,  6, 11,  8, 14,  7,
        12]], dtype=int64)

In [264]:
import os
import cv2
import numpy as np


from keras.preprocessing import image
from tensorflow.python.keras.models import load_model
from PIL import Image

pokemon_model=load_model('model2.h5')

# categories=['bug', 'dragon', 'electricity', 'esp', 'evil', 'fairy', 'fight', 'fire', 'ghost', 'grass', 'ice', 'land', 'normal', 'posion', 'rock', 'steel', 'water']
categories=['벌레', '드래곤', '전기', '에스퍼', '악', '요정', '격투', '불꽃', '고스트', '풀', '얼음', '땅', '노멀', '독', '바위', '강철', '물']

# file = request.files['original-file']     #파일 업로드
# filename = file.filename   #파일 읽기
# absolute_path = os.path.join('images', filename)   #경로를 병합하여 새 경로 생성
absolute_path = image.load_img('pokemon-test-image/fire/윈디_120.jpg')
#  ,target_size=(150,150))

# file.save(absolute_path)  # 업로드된 파일 저장

absolute_path = absolute_path.resize((150, 150))
x = image.img_to_array(absolute_path)
# x = x.resize((1,150,150,3))
x = x.reshape((1,) + x.shape)
x = x/255.

# predict=pokemon_model.predict(x)
# result=np.argmax(predict)
# result=categories[result]

predict=pokemon_model.predict(x)
result=np.argmax(predict)
result=categories[np.argmax(predict)]

result={result: (100*np.max(predict)).round(2)}
# np.max(predict).round(2)
result

{'노멀': 26.14}