In [1]:
import numpy as np

In [9]:
a = [1, 2, 3, 4]
npa = np.array(a, dtype=np.float32)

In [10]:
a

[1, 2, 3, 4]

In [11]:
npa

array([1., 2., 3., 4.], dtype=float32)

In [12]:
npa.dtype

dtype('float32')

In [13]:
# ndarray는 동일한 자료형의 데이터만 관리
np.array([1, '2', 3, '4'])

array(['1', '2', '3', '4'], dtype='<U11')

In [16]:
# ndarray는 동일한 자료형의 데이터만 관리
np.array([1, '2', 3, '4'], dtype=np.int32)

array([1, 2, 3, 4])

In [19]:
b = [ [1, 2], [3, 4], [5, 6] ] # 리스트의 리스트
npb = np.array(b) # 2차원 배열

In [20]:
b

[[1, 2], [3, 4], [5, 6]]

In [21]:
npb

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
c = [1, 2, 3, 4, 5]
npc1 = np.array(c)
npc2 = np.array(c, ndmin=2)

In [23]:
npc1

array([1, 2, 3, 4, 5])

In [24]:
npc2

array([[1, 2, 3, 4, 5]])

In [25]:
npc1.ndim, npc2.ndim

(1, 2)

In [26]:
d = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
npd = np.array(d)

In [28]:
print( npd.ndim )
print( npd.shape )
npd

2
(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# npe = np.empty([7, 5], dtype=np.int32)
# npe = np.zeros([7, 5], dtype=np.int32)
npe = np.ones([7, 5], dtype=np.int32)
npe

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
f = range(1, 10)
npf = np.arange(1, 10)
npf = np.arange(1, 10, 2)
npf

array([1, 3, 5, 7, 9])

In [37]:
npg = np.linspace(0, 10, num=4, endpoint=False)
npg

array([0. , 2.5, 5. , 7.5])

In [57]:
nph = np.arange(10)
print( nph[4] ) # 단일 값 반환
print( nph[2:6] )
print( nph[:6] )
print( nph[2:] )
print( nph[:] )
print( nph[::3] )

4
[2 3 4 5]
[0 1 2 3 4 5]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


In [67]:
# h = [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ]
# nph = np.array(h)
nph = np.arange(1, 13).reshape( (3, 4) )
nph

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
# nph[1]
# nph[0:2]
# nph[1][2]
# nph[1,2]
# nph[:2, 2:]
nph[:, 3]


24

In [78]:
npi = np.arange(1, 13)
print(npi[1])
print(npi[2:5])
print(npi[[0, 4, 6, 9]])

2
[3 4 5]
[ 1  5  7 10]


In [82]:
npi = np.arange(1, 13).reshape((4,3))
npi

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
rows = np.array([0, 0, 3, 3])
cols = np.array([0, 2, 0, 2])
npi[rows,cols]

array([ 1,  3, 10, 12])

In [85]:
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
npi[rows, cols]

array([[ 1,  3],
       [10, 12]])

In [86]:
npj = np.arange(10)
npj

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
npj < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [87]:
npj[npj < 5]

array([0, 1, 2, 3, 4])

In [92]:
npj[
    [True, True, False, True, False, 
     True, False, True, False, False]
    ]

array([0, 1, 3, 5, 7])

In [94]:
npk = np.array([1, 2, np.nan, 4, 5, np.nan, 6])
print(npk)
print(npk[np.isnan(npk)])
print(npk[~np.isnan(npk)])

[ 1.  2. nan  4.  5. nan  6.]
[nan nan]
[1. 2. 4. 5. 6.]


In [97]:
npl = np.arange(10)
# npl
npl + 5 # npl + [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
# b = np.array([[1.0,2.0,3.0], [1.0,2.0,3.0], [1.0,2.0,3.0], [1.0,2.0,3.0] ])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [126]:
# 4열부터 52열까지의 데이터를 읽어서 Numpy 배열로 만드세요
import csv

with open('data-files/subway-data.csv', encoding="utf-8") as f:
    reader = csv.reader(f)
    
    subway_data_list = list(reader)

In [ ]:
subway_data_list[2]

In [131]:
import numpy as np

subway_data_array = np.array(subway_data_list[2:])

array([['813', '16', '8,478', '5,920', '10,736', '37,191', '29,922',
        '80,358', '53,921', '170,533', '39,251', '114,126', '38,103',
        '55,958', '46,762', '47,869', '55,232', '49,303', '57,055',
        '51,283', '48,828', '49,860', '64,421', '50,831', '71,948',
        '51,102', '115,171', '60,380', '176,221', '63,184', '86,920',
        '45,583', '61,811', '31,079', '59,285', '25,122', '41,290',
        '18,647', '15,258', '10,959', '11', '1,427', '0', '0', '0', '0',
        '0', '0'],
       ['30', '1', '1,557', '3,131', '2,914', '15,686', '5,627',
        '57,041', '6,957', '138,115', '7,841', '67,596', '8,553',
        '27,971', '12,095', '26,249', '13,668', '22,574', '17,272',
        '22,013', '22,049', '18,517', '28,018', '16,094', '32,000',
        '13,771', '59,053', '14,576', '115,293', '15,487', '46,640',
        '7,610', '34,966', '4,267', '34,047', '3,807', '22,202', '2,630',
        '7,325', '1,755', '5', '143', '0', '1', '0', '1', '0', '0']],
      dtype='<U

In [ ]:
# !pip install pandas

In [ ]:
# 데이터 확인
import csv

with open('data-files/subway-data.csv', encoding="utf-8") as f:
    reader = csv.reader(f)
    next(reader)
    next(reader)
    
    with open('data-files/subway-data-modified.csv', 'w', encoding="utf-8") as f2:        
        for idx, row in enumerate(reader):
            row2 = map(lambda x: x.replace(",", ""), row)
            f2.write(",".join(list(row2)))
            f2.write('\n')
            
print("end of file")

In [167]:
import numpy as np

ar = np.genfromtxt('data-files/subway-data-modified.csv', 
                   delimiter=',', 
                   encoding="utf-8", 
                   dtype='U')


In [169]:
ar[:, 4:-1]

array([['813', '16', '8478', ..., '0', '0', '0'],
       ['30', '1', '1557', ..., '1', '0', '0'],
       ['75', '4', '3014', ..., '1', '0', '0'],
       ...,
       ['11', '1', '748', ..., '0', '0', '0'],
       ['2', '0', '350', ..., '0', '0', '0'],
       ['20', '0', '892', ..., '0', '0', '0']], dtype='<U19')

In [159]:
import pandas as pd

In [166]:
df = pd.read_csv('data-files/subway-data.csv', 
                 encoding="utf-8",
                 skiprows=2)

In [164]:
df.head()

2020-05  1호선  0150   서울역  813  16   8,478  5,920 10,736  37,191  ...  \
0  2020-05  1호선   151    시청   30   1   1,557  3,131  2,914  15,686  ...   
1  2020-05  1호선   152    종각   75   4   3,014  4,160  3,319  23,724  ...   
2  2020-05  1호선   153  종로3가  201  22   4,118  2,484  3,435  12,520  ...   
3  2020-05  1호선   154  종로5가   29   1   1,708  3,562  2,587  15,233  ...   
4  2020-05  1호선   155   동대문  620  13  13,095  2,198  9,135   7,173  ...   

   10,959  11  1,427  0 0.1 0.2 0.3 0.4 0.5  2020-06-03 11:49:09  
0   1,755   5    143  0   1   0   1   0   0  2020-06-03 11:49:09  
1   2,735  58    161  0   0   0   1   0   0  2020-06-03 11:49:09  
2   3,525  53    698  0   0   0   0   0   0  2020-06-03 11:49:09  
3   2,131  15    290  0   1   0   0   0   0  2020-06-03 11:49:09  
4  10,298  25  1,012  0   0   0   0   0   0  2020-06-03 11:49:09  

[5 rows x 53 columns]