In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [2]:
cancer = load_breast_cancer()

In [3]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
import pandas as pd

cancer_df = pd.DataFrame(cancer['data'], columns=cancer['feature_names'])

In [5]:
cancer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [6]:
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [8]:
# (문제 1) 훈련 세트와 테스트 세트로 분할
# - 테스트 데이터 비율 : 20%
# - 재현 가능하도록 random_seed 지정
# - 타겟의 각 범주 구성비를 훈련 세트와 테스트 세트에 동일하게 유지


In [7]:
from sklearn.model_selection import train_test_split

In [10]:
X,y=cancer['data'], cancer['target']

In [13]:
X.shape , y.shape

((569, 30), (569,))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape 

((455, 30), (114, 30), (455,), (114,))

In [14]:
# (문제 2-1) 문제 1에서 만든 데이터셋을 사용해서 다음 작업을 수행하세요
# - LogisticRegression 모델 생성
# - 모델 훈련 (교차 검증 - cross_validation 사용)
# - 훈련 데이터와 테스트 데이터로 평가

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

In [29]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_train, y_train), lr.score(X_test, y_test)

c:\programdata\miniconda3\envs\hoseo\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(0.9560439560439561, 0.956140350877193)

In [34]:
cross_validate(lr, X_train, y_train) , cross_validate(lr, X_test, y_test)

c:\programdata\miniconda3\envs\hoseo\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
c:\programdata\miniconda3\envs\hoseo\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear

({'fit_time': array([0.03797626, 0.03697634, 0.03098059, 0.02898216, 0.03098106]),
  'score_time': array([0.00100017, 0.00099945, 0.        , 0.        , 0.        ]),
  'test_score': array([0.97802198, 0.9010989 , 0.96703297, 0.95604396, 0.9010989 ])},
 {'fit_time': array([0.01998758, 0.02198601, 0.02098727, 0.0209868 , 0.02598476]),
  'score_time': array([0.00099945, 0.        , 0.        , 0.        , 0.        ]),
  'test_score': array([0.95652174, 1.        , 0.95652174, 0.95652174, 0.90909091])})

In [36]:
# (문제 2-2) 문제 1에서 만든 데이터셋을 사용해서 다음 작업을 수행하세요
# - SVC 모델 생성
# - cross_validation 함수를 사용해서 교차 검증  수행
# - 모델 훈련
# - 훈련 데이터와 테스트 데이터로 평가

from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_validate


In [38]:
svc = SVC() 
svc.fit(X_train, y_train)
svc.score(X_train, y_train), svc.score(X_test, y_test)

(0.9142857142857143, 0.9473684210526315)

In [43]:
cross_validate(svc, X_train, y_train) , cross_validate(svc, X_test, y_test)

({'fit_time': array([0.00299859, 0.00299788, 0.00299978, 0.00299764, 0.00299835]),
  'score_time': array([0.00099945, 0.        , 0.00099921, 0.00099921, 0.00099945]),
  'test_score': array([0.92307692, 0.87912088, 0.96703297, 0.86813187, 0.87912088])},
 {'fit_time': array([0.        , 0.00099945, 0.        , 0.        , 0.00100136]),
  'score_time': array([0.00099945, 0.        , 0.        , 0.00099945, 0.        ]),
  'test_score': array([1.        , 0.95652174, 0.91304348, 0.82608696, 1.        ])})

In [44]:
mms = MinMaxScaler()
mms.fit(X_train)
X_train_scaled = mms.transform(X_train)
X_test_scaled = mms.transform(X_test)

In [45]:
svc.fit(X_train_scaled, y_train)
svc.score(X_train_scaled, y_train), svc.score(X_test_scaled, y_test)

(0.9846153846153847, 0.9736842105263158)

In [47]:
# (문제 2-3) 문제 1에서 만든 데이터셋을 사용해서 다음 작업을 수행하세요
# - RandomForest 모델 생성
# - cross_validation 함수를 사용해서 교차 검증  수행
# - 모델 훈련
# - 훈련 데이터와 테스트 데이터로 평가

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate


In [48]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_train, y_train), rf.score(X_test, y_test)

(1.0, 0.9649122807017544)

In [49]:
cross_validate(rf, X_train, y_train) , cross_validate(rf, X_test, y_test)

({'fit_time': array([0.19188118, 0.17888999, 0.18188834, 0.18188643, 0.18189001]),
  'score_time': array([0.00999594, 0.00999355, 0.00999427, 0.01199269, 0.00999355]),
  'test_score': array([0.95604396, 0.94505495, 0.97802198, 0.95604396, 0.95604396])},
 {'fit_time': array([0.1439116 , 0.14590812, 0.14890671, 0.14790916, 0.1479094 ]),
  'score_time': array([0.00999355, 0.01099563, 0.00999355, 0.010993  , 0.00999355]),
  'test_score': array([1.        , 0.95652174, 0.95652174, 0.86956522, 0.86363636])})

In [59]:
# (문제 3) 문항 2에서 만든 각 모델을 사용해서 훈련데이터와 테스트데이터의 정확도, F1-Score, AUC 값을 출력하고 비교

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

print(accuracy_score(y_test, lr.predict(X_test)))
print(f1_score(y_test, lr.predict(X_test)))
print(roc_auc_score(y_test, lr.predict(X_test)))

print('********')
print(accuracy_score(y_test, svc.predict(X_test)))
print(f1_score(y_test, svc.predict(X_test)))
print(roc_auc_score(y_test, svc.predict(X_test)))


print('********')
print(accuracy_score(y_test, rf.predict(X_test)))
print(f1_score(y_test, rf.predict(X_test)))
print(roc_auc_score(y_test, rf.predict(X_test)))

0.956140350877193
0.9655172413793103
0.9464461185718965
********
0.37719298245614036
0.0
0.5
********
0.9649122807017544
0.9722222222222222
0.9580740255486406


In [104]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris['data']

In [105]:
# iris

In [128]:
# (문제 4-1) iris 데이터셋을 3개의 군집으로 나누는 모델을 훈련하고 각 데이터의 군집 값을 출력하세요

from sklearn.cluster import KMeans

X=iris['data']
y=iris.target

km=KMeans(n_clusters=3)
km.fit(X)

KMeans(n_clusters=3)

In [129]:
print(km.labels_)
print(km.predict(X))   
print(km.cluster_centers_)   #cluster_centers_ 속성에 저장된 클러스터 중심

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]
[[6.85       3.07368421 5.74210526 2.07105263]
 [5.006      3.428      1.462      0.246     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]]


In [132]:
y_pred = km.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [122]:
# (문제 4-2)  각 군집의 통계량을 출력하고 차이를 확인하세요

import numpy as np
import pandas as pd

In [133]:
iris_df = pd.DataFrame(X, columns=['sepal length', 'sepal width', 'petal length', 'petal width'])
iris_df['species'] = y_pred
iris_df.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [136]:
iris_df.groupby(['species']).describe()

sepal length                                                 \
               count      mean       std  min    25%  50%  75%  max   
species                                                               
0               38.0  6.850000  0.494155  6.1  6.425  6.7  7.2  7.9   
1               50.0  5.006000  0.352490  4.3  4.800  5.0  5.2  5.8   
2               62.0  5.901613  0.466410  4.9  5.600  5.9  6.2  7.0   

        sepal width            ... petal length      petal width            \
              count      mean  ...          75%  max       count      mean   
species                        ...                                           
0              38.0  3.073684  ...        6.000  6.9        38.0  2.071053   
1              50.0  3.428000  ...        1.575  1.9        50.0  0.246000   
2              62.0  2.748387  ...        4.800  5.1        62.0  1.433871   

                                                
              std  min    25%  50%    75%  max  
species                                         
0        0.279872  1.4  1.825  2.1  2.300  2.5  
1        0.105386  0.1  0.200  0.2  0.300  0.6  
2        0.297500  1.0  1.300  1.4  1.575  2.4  

[3 rows x 32 columns]