In [ ]:
# 패키지 설치
# !pip install scikit-learn
# !pip install mglearn       ->저자가 만든 예제 패키지 설치

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()   #붓꽃 종별
# iris

In [28]:
# print(type(iris))  #<class 'sklearn.utils.Bunch'> => 딕셔너리 같음.
# iris['data'][:5]  #feature (설명변수)
# iris['feature_names'] # 설명변수 데이터 이름
# iris['target'][:5] # label (목적변수 )
# iris['target'][[0,50,100]]  
# iris['target_names'] #목적변수 데이터 이름
# iris['DESCR']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
#훈련 데이터/ 테스트 데이터 분할 
# 재현 가능한 데이터를 뽑아야 함. 어느 데이터를 뽑아도 결과가 나올수 있게 random 사용.
# X_train, X_test, y_train, y_test = train_test_split(iris['data'],iris['target'], random_state=42)
X_train, X_test, y_train, y_test = train_test_split(iris['data'],iris['target'], random_state=0)

In [7]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape      #대략 25% 잡고 진행됨

((112, 4), (38, 4), (112,), (38,))

In [8]:
# 길이, 너비 데이터로 품종을 찾겠다는 내용

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
knn = KNeighborsClassifier() #알고리즘이 적용된 예측기
knn.fit(X_train, y_train)   #훈련, 적합 시켜 규칙 찾으라는 <모델 훈련(학습)>.

KNeighborsClassifier()

In [11]:
predicted_y = knn.predict(X_test) # 테스트데이터로 예측  
print(predicted_y[:5])
print(iris["target_names"][predicted_y[:5]])

[2 1 0 2 0]
['virginica' 'versicolor' 'setosa' 'virginica' 'setosa']


In [14]:
predicted_y[:5], y_test[:5]
(predicted_y == y_test).sum()  # random_state=42 인경우 -> true : 38
(predicted_y == y_test).sum() / len(y_test) # 1.o ->100% 맞췄다는 의미  #accuracy

0.9736842105263158

In [15]:
predicted_y2 = knn.predict(X_train) #훈련 데이터로 예측
(predicted_y2 == y_train).sum() / len(y_train)

# 훈련데이터, 테스트데이터 비교해서 과대적합, 과소적합 확인

0.9732142857142857

In [ ]:
# mglearn.datasets 패키지의 make_forge 함수가 반환하는 데이터셋으로 knn 모델 테스트
# 1. 데이터 로딩
# 2. 훈련데이터, 테스트 데이터 분할
# 3. 모델 생성
# 4. 훈련 데이터로 모델 훈련
# 5. 훈련 데이터로 예측 - 정확도 평가
# 6. 테스트데이터로 예측 - 정확도 평가

In [74]:
# 강사님 풀이
# mglearn.datasets 패키지의 make_forge 함수가 반환하는 데이터셋으로 knn 모델 테스트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from mglearn.datasets import make_forge
# 1. 데이터 로딩
X, y = make_forge()

# 2. 훈련데이터, 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)   # random_state 고정하면 나오는 값이 같다.(데이터가 계속 바뀌면 비교 판단 힘들기 때문에 고정시켜야함.)

# 3. 모델 생성
knn=KNeighborsClassifier(n_neighbors=3)

# 4. 훈련 데이터로 모델 훈련
knn.fit(X_train, y_train)     # 정답을 준다. 

# 5. 훈련 데이터로 예측 - 정확도 평가
predicted_train_y = knn.predict(X_train)
train_accuracy = (predicted_train_y == y_train).sum() / len(y_train)

# 6. 테스트데이터로 예측 - 정확도 평가
predicted_test_y = knn.predict(X_test)
test_accuracy = (predicted_test_y == y_test).sum() / len(y_test)

train_accuracy, test_accuracy

c:\programdata\miniconda3\envs\hoseo\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn
  warnings.warn(msg, category=FutureWarning)


(0.9473684210526315, 0.8571428571428571)

In [16]:
#내가 한거
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split   # 데이터 분할
from sklearn.neighbors import KNeighborsClassifier 
from mglearn.datasets import make_forge   # mglearn.datasets 패키지의 make_forge 함수가 반환하는 데이터셋

In [57]:
# 1. 데이터 로딩
forge = make_forge() 
# type(forge)
# forge

In [36]:
from sklearn.model_selection import train_test_split

In [46]:
# 2. 훈련데이터, 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(forge[0], forge[1] ,random_state=42)

In [47]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((19, 2), (7, 2), (19,), (7,))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 

In [51]:
# 3. 모델 생성
knn=KNeighborsClassifier()
# 4. 훈련 데이터로 모델 훈련
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [55]:
# 5. 훈련 데이터로 예측 - 정확도 평가
predicted_y = knn.predict(X_train)
predicted_y[:5]
print(predicted_y[:10], y_train[:10])
(predicted_y == y_train).sum() / len(y_train)

[0 0 1 1 0 1 0 1 0 0] [0 0 1 1 0 1 0 0 0 0]


0.9473684210526315

In [63]:
# 6. 테스트데이터로 예측 - 정확도 평가
predicted_y2 = knn.predict(X_test)
print(predicted_y2[:5] , y_test[:5])
(predicted_y2 == y_test).sum()/len(y_test)

[1 1 1 1 0] [1 1 1 1 1]


0.8571428571428571