In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [5]:
iris=load_iris()
print(np.unique(iris.target)) 
X,y=iris['data'], iris['target']

[0 1 2]


In [6]:
#다중분류 확인
from sklearn.svm import SVC

In [9]:
svc = SVC(probability=True)
svc.fit(X, y)
svc.score(X,y)

0.9733333333333334

In [22]:
print(svc.predict([X[0]]))
print(svc.predict_proba([X[0]]))
print(svc.decision_function([X[0]]))

[0]
[[0.97804713 0.01389539 0.00805749]]
[[ 2.23543749  1.16096255 -0.25650709]]


In [14]:
v = svc.decision_function(X)   #가중치
m = np.argmax(v, axis=1)      #각 행에서 가장 큰 값의 위치 반환
(y == m).sum() / len(m)

0.9733333333333334

In [23]:
v2 = svc.predict_proba(X)    #확률
# print(np.sum(v2, axis=1))   # 개별 값은 확률, 각 행의 합은 1 
m2 = np.argmax(v2, axis=1)   #각 행에서 가장 큰 값의 위치 반환
# m2
(y==m2).sum()/len(y)

0.98

In [25]:
# 메모
# m2 == svc.predict(X)
# 타겟별 확률이 얼마인지 확인을 위해 predict 사용
# ex) target (0:19 , 1: 21, 2: 9) -> target predict : 1 (최종값)///// 내부적 가중치값이 가장 큰 것을 예측 최종값을 가져와 사용